# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binomial_coef <- function(n, k) {
    .Call('_fEGarch_binomial_coef', PACKAGE = 'fEGarch', n, k)
}

ald_first_abs_mom <- function(P) {
    .Call('_fEGarch_ald_first_abs_mom', PACKAGE = 'fEGarch', P)
}

pdf_ald <- function(x, mu, sigt, P) {
    .Call('_fEGarch_pdf_ald', PACKAGE = 'fEGarch', x, mu, sigt, P)
}

pdf_ald_v1 <- function(x, P) {
    .Call('_fEGarch_pdf_ald_v1', PACKAGE = 'fEGarch', x, P)
}

pdf_skew_sald <- function(x, P, skew) {
    .Call('_fEGarch_pdf_skew_sald', PACKAGE = 'fEGarch', x, P, skew)
}

sigt_aparch_forecast_short <- function(et, sigt, omega, phi, beta, gamma, delta, E_e, horizon) {
    .Call('_fEGarch_sigt_aparch_forecast_short', PACKAGE = 'fEGarch', et, sigt, omega, phi, beta, gamma, delta, E_e, horizon)
}

sigt_aparch_Cpp <- function(x, mu, phi, beta, gamma, delta, omega, sigd_init, etransf_init) {
    .Call('_fEGarch_sigt_aparch_Cpp', PACKAGE = 'fEGarch', x, mu, phi, beta, gamma, delta, omega, sigd_init, etransf_init)
}

aparch_sim_Cpp <- function(innov, omega, phi, beta, gamma, delta, n_out, mu, E_sigd) {
    .Call('_fEGarch_aparch_sim_Cpp', PACKAGE = 'fEGarch', innov, omega, phi, beta, gamma, delta, n_out, mu, E_sigd)
}

forecast_arma_Cpp <- function(x, et, mu, ma_e, ar_e, horizon) {
    .Call('_fEGarch_forecast_arma_Cpp', PACKAGE = 'fEGarch', x, et, mu, ma_e, ar_e, horizon)
}

forecast_farima_Cpp <- function(x, mu, coef_inf, horizon) {
    .Call('_fEGarch_forecast_farima_Cpp', PACKAGE = 'fEGarch', x, mu, coef_inf, horizon)
}

fitted_arma_Cpp <- function(x, mu, ma, ar) {
    .Call('_fEGarch_fitted_arma_Cpp', PACKAGE = 'fEGarch', x, mu, ma, ar)
}

arma_sim_Cpp <- function(innov, mu, ma, ar, nout) {
    .Call('_fEGarch_arma_sim_Cpp', PACKAGE = 'fEGarch', innov, mu, ma, ar, nout)
}

farima_sim_Cpp <- function(innov, mu, coef_inf, nout) {
    .Call('_fEGarch_farima_sim_Cpp', PACKAGE = 'fEGarch', innov, mu, coef_inf, nout)
}

sigt_egarch_forecast_shortCpp <- function(et, sigt, omega, phi, alpha, beta, E_asy, E_mag, powers, modulus, mode, horizon) {
    .Call('_fEGarch_sigt_egarch_forecast_shortCpp', PACKAGE = 'fEGarch', et, sigt, omega, phi, alpha, beta, E_asy, E_mag, powers, modulus, mode, horizon)
}

sigt_egarch_forecast_longCpp <- function(et, coef_inf, kappa, gamma, E_asy, E_mag, Elnsig2, powers, modulus, mode, horizon) {
    .Call('_fEGarch_sigt_egarch_forecast_longCpp', PACKAGE = 'fEGarch', et, coef_inf, kappa, gamma, E_asy, E_mag, Elnsig2, powers, modulus, mode, horizon)
}

signCpp <- function(val) {
    .Call('_fEGarch_signCpp', PACKAGE = 'fEGarch', val)
}

signVecCpp <- function(vals) {
    .Call('_fEGarch_signVecCpp', PACKAGE = 'fEGarch', vals)
}

sigt_egarch_shortCpp <- function(x, mu, omega, phi, alpha, beta, E_asy, E_mag, powers, modulus, mode, lnsig2_init) {
    .Call('_fEGarch_sigt_egarch_shortCpp', PACKAGE = 'fEGarch', x, mu, omega, phi, alpha, beta, E_asy, E_mag, powers, modulus, mode, lnsig2_init)
}

sigt_egarch_longCpp <- function(x, mu, coef_inf, kappa, gamma, E_asy, E_mag, Elnsig2, powers, modulus, mode) {
    .Call('_fEGarch_sigt_egarch_longCpp', PACKAGE = 'fEGarch', x, mu, coef_inf, kappa, gamma, E_asy, E_mag, Elnsig2, powers, modulus, mode)
}

egarch_longmemo_type_sim <- function(innov, omega_sig, coef_inf, kappa, gamma, n_out, mu, E_mag, E_asy, powers, modulus, mode, np2) {
    .Call('_fEGarch_egarch_longmemo_type_sim', PACKAGE = 'fEGarch', innov, omega_sig, coef_inf, kappa, gamma, n_out, mu, E_mag, E_asy, powers, modulus, mode, np2)
}

egarch_shortmemo_type_sim <- function(innov, omega_sig, ar_coef, ma_coef, kappa, gamma, n_out, mu, E_mag, E_asy, powers, modulus, mode) {
    .Call('_fEGarch_egarch_shortmemo_type_sim', PACKAGE = 'fEGarch', innov, omega_sig, ar_coef, ma_coef, kappa, gamma, n_out, mu, E_mag, E_asy, powers, modulus, mode)
}

sigt_fiaparch_forecast <- function(rt, coef_inf, omega, gamma, delta, E_const, horizon) {
    .Call('_fEGarch_sigt_fiaparch_forecast', PACKAGE = 'fEGarch', rt, coef_inf, omega, gamma, delta, E_const, horizon)
}

fiaparch_sim_Cpp <- function(innov, omega, coef_inf, gamma, delta, n_out, mu) {
    .Call('_fEGarch_fiaparch_sim_Cpp', PACKAGE = 'fEGarch', innov, omega, coef_inf, gamma, delta, n_out, mu)
}

sigt_garch_Cpp <- function(x, mu, phi, beta, omega, sig2_init) {
    .Call('_fEGarch_sigt_garch_Cpp', PACKAGE = 'fEGarch', x, mu, phi, beta, omega, sig2_init)
}

pdf_ged <- function(rt, mu, sigt, shape) {
    .Call('_fEGarch_pdf_ged', PACKAGE = 'fEGarch', rt, mu, sigt, shape)
}

pdf_ged_v1 <- function(rt, shape) {
    .Call('_fEGarch_pdf_ged_v1', PACKAGE = 'fEGarch', rt, shape)
}

pdf_skew_sged <- function(x, shape, skew) {
    .Call('_fEGarch_pdf_skew_sged', PACKAGE = 'fEGarch', x, shape, skew)
}

d_coefs_inv <- function(d, max_i) {
    .Call('_fEGarch_d_coefs_inv', PACKAGE = 'fEGarch', d, max_i)
}

d_coefs <- function(d, max_i) {
    .Call('_fEGarch_d_coefs', PACKAGE = 'fEGarch', d, max_i)
}

poly_inv <- function(ar, max_i) {
    .Call('_fEGarch_poly_inv', PACKAGE = 'fEGarch', ar, max_i)
}

sigt_loggarch_forecast_short <- function(et, sigt, omega, phi, psi, Elneta2, horizon) {
    .Call('_fEGarch_sigt_loggarch_forecast_short', PACKAGE = 'fEGarch', et, sigt, omega, phi, psi, Elneta2, horizon)
}

sigt_loggarch_forecast_long <- function(et, coef_inf, Elneta2, Elnsig2, horizon) {
    .Call('_fEGarch_sigt_loggarch_forecast_long', PACKAGE = 'fEGarch', et, coef_inf, Elneta2, Elnsig2, horizon)
}

sigt_loggarch_long <- function(x, mu, coef_inf, Elneta2, Elnsig2) {
    .Call('_fEGarch_sigt_loggarch_long', PACKAGE = 'fEGarch', x, mu, coef_inf, Elneta2, Elnsig2)
}

sigt_loggarch_short <- function(x, mu, omega, phi, psi, Elneta2, lnsig2_init) {
    .Call('_fEGarch_sigt_loggarch_short', PACKAGE = 'fEGarch', x, mu, omega, phi, psi, Elneta2, lnsig2_init)
}

loggarch_shortmemo_type_sim <- function(innov, omega_sig, ar_coef, ma_coef, n_out, mu, Econst) {
    .Call('_fEGarch_loggarch_shortmemo_type_sim', PACKAGE = 'fEGarch', innov, omega_sig, ar_coef, ma_coef, n_out, mu, Econst)
}

loggarch_longmemo_type_sim <- function(innov, omega_sig, coef_inf, n_out, mu, Econst, np2) {
    .Call('_fEGarch_loggarch_longmemo_type_sim', PACKAGE = 'fEGarch', innov, omega_sig, coef_inf, n_out, mu, Econst, np2)
}

pdf_norm <- function(rt, mu, sigt) {
    .Call('_fEGarch_pdf_norm', PACKAGE = 'fEGarch', rt, mu, sigt)
}

pdf_norm_v1 <- function(rt) {
    .Call('_fEGarch_pdf_norm_v1', PACKAGE = 'fEGarch', rt)
}

pdf_skew_snorm <- function(x, skew) {
    .Call('_fEGarch_pdf_skew_snorm', PACKAGE = 'fEGarch', x, skew)
}

pdf_std <- function(rt, mu, sigt, df) {
    .Call('_fEGarch_pdf_std', PACKAGE = 'fEGarch', rt, mu, sigt, df)
}

pdf_std_v1 <- function(rt, df) {
    .Call('_fEGarch_pdf_std_v1', PACKAGE = 'fEGarch', rt, df)
}

pdf_skew_sstd <- function(x, df, skew) {
    .Call('_fEGarch_pdf_skew_sstd', PACKAGE = 'fEGarch', x, df, skew)
}

